project:
  type: book

book:
  title: "First-ever Quarto Book"
  author: "Isley Jean-Pierre"
  date: "2/15/2026"
  cover-image: QB.png
  chapters:
    - index.qmd
    - 01-R-Script-Resubmission-Assignment.qmd
    - 02-Continuing-Law-Firm-Analysis---Part-2-.qmd
    - 03-Midterm.qmd
    - 04-NBA-Analytics.qmd
    - 05-Florida-Crime-Analytics.qmd
    - 06-Streaming-Analytics.qmd
    - 07-Wage-Analytics.qmd
    - 08-Shiny-RMarkdown-Assignment.qmd
    - 09-References.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

